[production]
address = "localhost"
port = 80
log = "critical"
template_dir = "assets/templates"

[development]
address = "localhost"
port = 8000
log = "normal"
template_dir = "assets/templates"

[staging]
address = "localhost"
port = 8000
log = "normal"
template_dir = "assets/templates"
